name: example-environment
python:
  version: 3.7
channels:
  - conda-forge
  - intel
dependencies:
  - gdal
  - python
  - numpy
  - pip
  - sklearn
  - shapely
  - rasterio
  - matplotlib
  - earthpy
  - geopandas
  - numpy
  - pandas
  - joblib
  - glob2
  - pip:
    - lithops
    - pickle-mixin
    - os-win





